import { pipe } from "../Function/index.js";
import { succeed } from "./core.js";
import { die } from "./die.js";
import { effectAsync } from "./effectAsync.js";
import { fail } from "./fail.js";
/**
 * Create an Effect that when executed will construct `promise` and wait for its result,
 * errors will be handled using `onReject`
 */

export function tryCatchPromise(promise, onReject, __trace) {
  return effectAsync(resolve => {
    promise().then(x => resolve(succeed(x))).catch(x => resolve(fail(onReject(x))));
  }, __trace);
}
/**
 * Create an Effect that when executed will construct `promise` and wait for its result,
 * errors will produce failure as `unknown`
 */

export function tryPromise(effect, __trace) {
  return effectAsync(resolve => {
    effect().then(x => resolve(succeed(x))).catch(x => resolve(fail(x)));
  }, __trace);
}
/**
 * Like tryPromise but produces a defect in case of errors
 */

export function promise(effect, __trace) {
  return effectAsync(resolve => {
    effect().then(x => resolve(succeed(x))).catch(x => resolve(die(x)));
  }, __trace);
}
//# sourceMappingURL=promise.js.map